name: Daily schedule

on:
  schedule:
    # Schedule for every day at 12:00 CEST
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  add-calendar-events:
    name: Add events to Sanity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Synchronize calendar events 📅
        run: pnpm add-calendar-events
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
