name: On PR

on:
  pull_request:

jobs:
  typical-workflow:
    name: Lint, format, test and build
    uses: bjerkio/workflows/.github/workflows/pnpm-typical.yml@v2

  formatting:
    name: Lint, format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Run formatter 💅
        run: pnpm format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
